name: mahmoud_fathi_start_tech_task
description: "start tech task implemented by mahmoud fathi ahmed."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  dartz: ^0.10.1
  get_storage: ^2.1.1
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: alexandria
      fonts:
        - asset: assets/fonts/AlexandriaFLF.ttf
          style: normal
        - asset: assets/fonts/AlexandriaFLF-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlexandriaFLF-Italic.ttf
          style: italic